### ISSUE TITLE
Allow all supported formats

### ISSUE THREAD

**Issue by gayfrogog** [SuperHackio/SuperJSON#4]
SuperBMD supports more than these four formats. You should have it either allow all the formats listed [here](https://github.com/assimp/assimp/wiki/The-asset-knowledge-base) or remove the restriction entirely.
![image](https://user-images.githubusercontent.com/37796393/47612068-cfd2a800-dac2-11e8-8265-74dbf2ac4e92.png)
~~and fix the typo in Autodesk~~

**Comment by SuperHackio** [comment]
These formats will be in support for V1.5.0.0
> * ***SuperJSON V1.5.0.0***
>    * *Autodesk Filmbox (.fbx)*
>    * *COLLAborative Design Activity (.dae)*
>    * *3ds Max 3DS (.3ds)*
>    * *Wavefront Object (.obj)*
>    * *Stereolithography (.stl)*
>    * *Blender (.blend)*
>    * *Additive Manufacturing Format (.amf)*
>    * *Open Game Engine Exchange (.ogex)*
>    * *DirectX (.x)*
>    * *X3D (.x3d)*
>    * *MDC (.mdc)*

Some did not make it onto this list as the program that makes them also export to a already-supported format.
